# SwiftLint configuration for Pi Desktop App
# Based on sindresorhus/swiftlint-config but customized for this project

excluded:
  - bin
  - data
  - "**/.build"
  - DerivedData
  - .swiftlint

# Explicitly enable rules (opt-in approach for clarity)
only_rules:
  # Style
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - colon
  - comma
  - computed_accessors_order
  - control_statement
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - implicit_getter
  - implicit_return
  - leading_whitespace
  - mark
  - modifier_order
  - no_space_in_method_call
  - operator_usage_whitespace
  - operator_whitespace
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - shorthand_optional_binding
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment
  - void_return

  # Lint
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - compiler_protocol_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - deployment_target
  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_direct_init
  - discouraged_none_name
  - duplicate_conditions
  - duplicate_enum_cases
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - generic_type_name
  - ibinspectable_in_extension
  - identical_operands
  - identifier_name
  - is_disjoint
  - joined_default_parameter
  - last_where
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
  - lower_acl_than_parent
  - no_extension_access_modifier
  - no_fallthrough_only
  - notification_center_detachment
  - ns_number_init_as_function_reference
  - nsobject_prefer_isequal
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_unit_test
  - prohibited_super_call
  - reduce_boolean
  - reduce_into
  - redundant_sendable
  - required_enum_case
  - self_binding
  - self_in_property_initialization
  - sorted_first_last
  - static_operator
  - static_over_final_class
  - strong_iboutlet
  - superfluous_disable_command
  - superfluous_else
  - toggle_bool
  - unavailable_condition
  - unavailable_function
  - unneeded_override
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - void_function_in_ternary
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition

# Rule configurations
deployment_target:
  macOS_deployment_target: '15'
  iOS_deployment_target: '18'

identifier_name:
  max_length:
    warning: 100
    error: 100
  min_length:
    warning: 1
    error: 1
  allowed_symbols:
    - '_'
  excluded:
    - 'x'
    - 'y'
    - 'z'
    - 'a'
    - 'b'
    - 'p'
    - 'id'
    - 'ok'
    - 'to'
    - 'vm'

trailing_comma:
  mandatory_comma: false
