# Local dev overlay. Reuses the same .dev/ paths as `pnpm dev`.
#
# Usage (from server/relay/):
#   docker compose -f compose.yaml -f compose.dev.yaml up
#
# Requires the nix dev shell (which sets PI_RELAY_*_DIR).
# RELAY_ENCRYPTION_KEY is loaded by the app from .env in the config dir.

services:
  relay:
    volumes:
      # Docker socket inside the VM (Lima/colima expose it at the standard path)
      - /var/run/docker.sock:/var/run/docker.sock
      # .dev/ dirs -- Lima mounts these at the same absolute path in the VM,
      # so sandbox bind mounts resolve correctly on the Docker host.
      - ${PI_RELAY_DATA_DIR}:${PI_RELAY_DATA_DIR}
      - ${PI_RELAY_CONFIG_DIR}:${PI_RELAY_CONFIG_DIR}
      - ${PI_RELAY_STATE_DIR}:${PI_RELAY_STATE_DIR}
      - ${PI_RELAY_CACHE_DIR}:${PI_RELAY_CACHE_DIR}
    environment:
      PI_RELAY_DATA_DIR: ${PI_RELAY_DATA_DIR}
      PI_RELAY_CONFIG_DIR: ${PI_RELAY_CONFIG_DIR}
      PI_RELAY_STATE_DIR: ${PI_RELAY_STATE_DIR}
      PI_RELAY_CACHE_DIR: ${PI_RELAY_CACHE_DIR}
