name: pi-mobile
options:
  bundleIdPrefix: ""
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Debug

configFiles:
  Debug: ../../Config/Debug.xcconfig
  Release: ../../Config/Release.xcconfig

settings:
  base:
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "6.0"

packages:
  PiCore:
    path: ../../packages/pi-core
  PiUI:
    path: ../../packages/pi-ui
  Textual:
    url: https://github.com/gonzalezreal/textual
    from: 0.2.0

targets:
  Pi:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - path: Sources
        type: syncedFolder
      - path: Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: $(PI_MOBILE_BUNDLE_ID)
        PRODUCT_NAME: Pi
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    dependencies:
      - package: PiCore
        product: PiCore
      - package: PiUI
        product: PiUI
      - package: Textual
        product: Textual

schemes:
  Pi Mobile:
    build:
      targets:
        Pi: all
    run:
      config: Debug
