name: "Docker Build and Push"
description: "Build multi-arch Docker image and push to GitHub Container Registry"

inputs:
  context:
    description: "Build context path"
    required: true
  image-name:
    description: "Image name (without registry prefix)"
    required: true
  platforms:
    description: "Target platforms"
    required: false
    default: "linux/amd64,linux/arm64"
  push:
    description: "Push to registry"
    required: false
    default: "true"
  registry:
    description: "Container registry"
    required: false
    default: "ghcr.io"
  github-token:
    description: "GitHub token for registry auth"
    required: true

outputs:
  tags:
    description: "Generated image tags"
    value: ${{ steps.meta.outputs.tags }}
  digest:
    description: "Image digest"
    value: ${{ steps.build.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Generate short SHA
      id: sha
      shell: bash
      run: echo "short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Extract Pi version from Dockerfile
      id: pi-version
      shell: bash
      run: |
        if [ -f "${{ inputs.context }}/Dockerfile" ]; then
          PI_VERSION=$(sed -n 's/^ARG PI_VERSION=//p' "${{ inputs.context }}/Dockerfile" | head -n 1)
          if [ -n "$PI_VERSION" ]; then
            echo "version=${PI_VERSION}" >> $GITHUB_OUTPUT
            echo "Found PI_VERSION: ${PI_VERSION}"
          else
            echo "version=" >> $GITHUB_OUTPUT
            echo "No PI_VERSION found in Dockerfile"
          fi
        else
          echo "version=" >> $GITHUB_OUTPUT
          echo "No Dockerfile found at ${{ inputs.context }}/Dockerfile"
        fi

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=sha,prefix=,format=short
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          type=raw,value=${{ steps.pi-version.outputs.version }},enable=${{ steps.pi-version.outputs.version != '' }}

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: GIT_COMMIT=${{ steps.sha.outputs.short }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
