name: "Docker Build and Push"
description: "Build multi-arch Docker image and push to GitHub Container Registry"

inputs:
  context:
    description: "Build context path"
    required: true
  image-name:
    description: "Image name (without registry prefix)"
    required: true
  platforms:
    description: "Target platforms"
    required: false
    default: "linux/amd64,linux/arm64"
  push:
    description: "Push to registry"
    required: false
    default: "true"
  registry:
    description: "Container registry"
    required: false
    default: "ghcr.io"
  github-token:
    description: "GitHub token for registry auth"
    required: true

outputs:
  tags:
    description: "Generated image tags"
    value: ${{ steps.meta.outputs.tags }}
  digest:
    description: "Image digest"
    value: ${{ steps.build.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Generate short SHA
      id: sha
      shell: bash
      run: echo "short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=sha,prefix=,format=short
          type=ref,event=branch
          type=ref,event=pr

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
