name: pi-native
options:
  bundleIdPrefix: ""
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

configFiles:
  Debug: ../../Config/Debug.xcconfig
  Release: ../../Config/Release.xcconfig

settings:
  base:
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "6.0"

targets:
  PiNativeiOS:
    type: application
    platform: iOS
    supportedDestinations: [iOS]
    sources:
      - path: Sources/Shared
        type: syncedFolder
      - path: Sources/iOS
        type: syncedFolder
      - path: Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Resources/iOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: $(PI_NATIVE_IOS_BUNDLE_ID)
        PRODUCT_NAME: Pi Native
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"

  PiNativemacOS:
    type: application
    platform: macOS
    sources:
      - path: Sources/Shared
        type: syncedFolder
      - path: Sources/macOS
        type: syncedFolder
      - path: Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Resources/macOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: $(PI_NATIVE_MAC_BUNDLE_ID)
        PRODUCT_NAME: Pi Native
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_APP_SANDBOX: YES

schemes:
  Pi Native iOS:
    build:
      targets:
        PiNativeiOS: all
    run:
      config: Debug
  Pi Native macOS:
    build:
      targets:
        PiNativemacOS: all
    run:
      config: Debug
