name: PiNative
options:
  bundleIdPrefix: me.aliou.pi-native
  deploymentTarget:
    iOS: '26.0'
    macOS: '26.0'
settings:
  base:
    SWIFT_VERSION: '6.0'
    PRODUCT_NAME: PiNative
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    ENABLE_PREVIEWS: YES
    DEVELOPMENT_ASSET_PATHS: "Sources/Shared/Preview Content"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    CLANG_ENABLE_MODULES: YES
    CLANG_ENABLE_OBJC_WEAK: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    GCC_WARN_DOCUMENTATION_COMMENTS: YES
    GCC_TREAT_WARNINGS_AS_ERRORS: NO

packages: {}

targets:
  PiNative-iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources/Shared
    settings:
      base:
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MACCATALYST: NO
    scheme:
      testTargets: []
  PiNative-macOS:
    type: application
    platform: macOS
    sources:
      - path: Sources/Shared
    settings:
      base:
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
    scheme:
      testTargets: []
